export type CategoriaEstudios = {
  id: string;
  title: string;
  estudios: string[];
};

/** Catálogo de estudios de laboratorio (sin precios). Fuente: lista ROGA 2026. */
export const LISTA_ESTUDIOS_CATEGORIAS: CategoriaEstudios[] = [
  {
    id: "hematologia",
    title: "Hematología",
    estudios: [
      "Biometría hemática",
      "VSG (Velocidad de sedimentación globular)",
      "Reticulocitos",
      "GPO/RH — grupo sanguíneo y factor RH",
      "Coombs directo",
      "Coombs indirecto",
    ],
  },
  {
    id: "coagulacion",
    title: "Coagulación",
    estudios: [
      "Tiempo de protrombina",
      "Tiempo de tromboplastina",
      "Tiempo de sangrado",
      "Tiempo de coagulación",
      "Fibrinógeno",
      "Dímero D",
    ],
  },
  {
    id: "microbiologia",
    title: "Microbiología",
    estudios: [
      "KOH (hongos — examen microscópico directo)",
      "BAAR (baciloscopia por muestra)",
      "BAAR — 3 muestras orina",
      "Exudado faríngeo",
      "Cultivo exudado vulvo-vaginal o cérvico-vaginal",
      "Cultivo de exudado uretral",
      "Espermocultivo",
      "Espermatobioscopia directa",
      "Espermatobioscopia indirecta (Sims-Huhner)",
      "Cultivo de expectoración",
      "Urocultivo",
      "Coprocultivo",
      "Cultivo de hongos (cultivo micológico)",
      "Cultivo microbiológico de uñas o manos",
      "Cultivo para detección de Neisseria gonorrhoeae",
      "Cultivo de líquidos serosos diversos (aerobios)",
      "Cultivo de exudado ótico u ocular",
      "Cultivo de abscesos y secreciones diversas",
      "Cultivo de exudado nasofaríngeo",
    ],
  },
  {
    id: "quimica-clinica",
    title: "Química clínica",
    estudios: [
      "Química sanguínea 3 (glu, urea, creat)",
      "Química sanguínea 4 (QS3 + ác. úrico)",
      "Química sanguínea 5 (QS4 + col)",
      "Química sanguínea 6 (QS5 + trig)",
      "Química sanguínea 7 (QS6 + HDL)",
      "Química sanguínea 8 (QS7 + BUN)",
      "Química sanguínea 12 (QS6 + P. lip + prot tot + albúm)",
      "Química sanguínea 18 (QS12 + PFH completas)",
      "Química sanguínea 24 (QS18 + ES4)",
      "Química sanguínea 27 (QS24 + GGT + AMY + LIP)",
      "Química sanguínea 28 (QS27 + DHL)",
      "Química sanguínea 30 (QS24 + ES6)",
      "Química sanguínea 32 (QS30 + CK + CKMB)",
      "Química sanguínea 35 (QS32 + HE + %SAT + cap. tot fij HE)",
      "Química sanguínea 36 (QS35 + ferritina)",
      "Química sanguínea 38 (QS36 + transferrina)",
      "Química sanguínea 44 (QS38 + PCR + FR + HbA1c + AELO)",
      "Química sanguínea 45 (QS44 + colinesterasa)",
      "Química sanguínea 6 / perfil lípidos completos",
      "Ácido úrico (sangre)",
      "Albúmina (sangre)",
      "Albúmina en orina ocasional o 24 h (microalbúmina) c/u",
      "Amilasa",
      "Amonio",
      "Bilirrubinas total, directa e indirecta (cada una)",
      "Bilirrubinas completas (BT, BD, BI)",
      "BUN",
      "Calcio sérico en sangre",
      "Calcio en orina",
      "Capacidad de fijación de hierro",
      "Cloro",
      "Colesterol",
      "Colesterol HDL",
      "Colesterol LDL",
      "Colinesterasa",
      "Colinesterasa eritrocitaria",
      "CPK",
      "CPK-MB",
      "Creatinina en sangre",
      "Creatinina en orina ocasional o 24 h",
      "Curva de tolerancia a la glucosa 1 h",
      "Curva de tolerancia a la glucosa 2 h",
      "Curva de tolerancia a la glucosa 3 h",
      "Curva de tolerancia a la glucosa 4 h",
      "Depuración de creatinina orina 24 h",
      "LDH — deshidrogenasa láctica (DHL)",
      "Electrolitos 3 (Na, K, Cl)",
      "Electrolitos 4 (Na, K, Ca, P)",
      "Ferritina",
      "Electrolitos 6 (Na, K, Cl, Ca, P, Mg)",
      "Fosfatasa alcalina",
      "Fósforo",
      "GGT — gamma glutamil transpeptidasa",
      "Globulina",
      "Glucosa",
      "Glucosa postprandial 2 h",
      "Hemoglobina glucosilada (A1c)",
      "Hierro",
      "Índice aterogénico",
      "Lipasa",
      "Magnesio",
      "PFH (BT, BD, BI, fosfat, TGO, TGP, prot, albúm, glob, rel. A/G)",
      "Porcentaje de saturación",
      "Perfil de lípidos",
      "Perfil de hierro I (HE, CAP, %SAT)",
      "Perfil de hierro II (HE, CAP, %SAT, FERR)",
      "Perfil de hierro III (HE, CAP, %SAT + FERR + TRANSF)",
      "Potasio",
      "Potasio en orina ocasional / 24 h",
      "Proteínas totales 24 h orina",
      "Proteínas totales en sangre",
      "RAC (relación albúmina/globulina)",
      "Sodio",
      "Tamiz gestacional para diabetes mellitus",
      "Transaminasa glutámico oxalacética (TGO)",
      "Transaminasa glutámico pirúvica (TGP)",
      "Triglicéridos",
      "Urea",
    ],
  },
  {
    id: "hormonas",
    title: "Hormonas",
    estudios: [
      "TSH",
      "T3 total",
      "T3 libre",
      "T4 total",
      "T4 libre",
      "Testosterona libre",
      "Testosterona total",
      "Ag CA-125",
      "Ag CA 19-9",
      "Ag CA 15-3",
      "Ag carcinoembrionario",
      "Insulina",
      "Alfafetoproteína",
      "FSH",
      "LH",
      "PSA libre",
      "PSA total",
      "Prolactina",
      "Estrógenos",
      "Progesterona",
      "Perfil ginecológico I (FSH, LH, EZ, PRL, PROG)",
      "Perfil ginecológico II (FSH, LH, EZ, PRL, PROG, TEST TOT)",
      "Estradiol",
      "Perfil tiroideo I (TSH, T4L)",
      "Perfil tiroideo II (TSH, T3 T, T4 T)",
      "Perfil tiroideo IV (TSH, T3 T, T4 T, T4 libre)",
      "Perfil tiroideo III (TSH, T3 T, T4 T, T4 libre, T3 libre)",
      "Vitamina D",
    ],
  },
  {
    id: "parasitologia",
    title: "Parasitología",
    estudios: [
      "Coproparasitoscópico 1",
      "Coproparasitoscópico 2",
      "Coproparasitoscópico 3",
      "Coprológico (amiba, CPS1, SHO, pH, CMF)",
      "Amiba en fresco",
      "Citología moco fecal (CMF)",
      "pH en heces",
      "Sangre en heces",
    ],
  },
  {
    id: "inmunologia",
    title: "Inmunología",
    estudios: [
      "Prueba de embarazo (PIE)",
      "β-hCG cuantificada",
      "VDRL",
      "Reacciones febriles",
      "Factor reumatoide",
      "PCR",
      "VIH",
      "Hepatitis A (Ac. IgM o totales) cuantificada",
      "Hepatitis A (Ac. IgM o totales) cualitativa",
      "Hepatitis B",
      "Hepatitis C",
      "Perfil hepatitis (hepatitis A, hepatitis B, hepatitis C)",
      "Perfil transmisión sexual 1 (HIV, VDRL)",
      "Perfil transmisión sexual 2 (HIV, VDRL, hepatitis B, hepatitis C)",
      "Perfil viral (hepatitis B, hepatitis C, HIV)",
    ],
  },
  {
    id: "orina",
    title: "Orina",
    estudios: [
      "EGO",
      "Creatinina en orina",
      "Antidoping 3",
      "Antidoping 5",
      "RAC",
      "Sodio, potasio orina c/u",
      "Urea en orina 24 h ocasional",
      "Proteinuria de una sola micción",
    ],
  },
];

export const LISTA_ESTUDIOS_TOTAL = LISTA_ESTUDIOS_CATEGORIAS.reduce(
  (sum, cat) => sum + cat.estudios.length,
  0,
);
